# Generated by Django 4.1.7 on 2023-02-16 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('servico_id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_servico', models.CharField(max_length=50)),
                ('preco_servico', models.DecimalField(decimal_places=2, max_digits=7)),
                ('disponibilidade', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('atendimento_id', models.AutoField(primary_key=True, serialize=False)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('R', 'Realizado'), ('C', 'Cancelado')], max_length=1)),
                ('forma_pagamento', models.CharField(choices=[('C', 'Cartão'), ('E', 'Espécie'), ('B', 'Boleto')], max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendente', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to=settings.AUTH_USER_MODEL)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='helper', to=settings.AUTH_USER_MODEL)),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='limpa_bem.servico')),
            ],
        ),
    ]
