# Generated by Django 4.1.7 on 2023-02-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limpa_bem', 'data'),
        ('limpa_bem', 'groups'),
    ]

    operations = [
    ]
