# Generated by Django 4.1.7 on 2023-02-18 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('limpa_bem', '0003_usuario_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data_servico',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
